name: PR checks

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  it_runs:
    name: Run tests against reference implementation
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x64"
    - uses: vmware-tanzu/carvel-setup-action@v1
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up kubeconfig
      run: |
        KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
        echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
    - name: Set up minikube
      uses: medyagh/setup-minikube@latest
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
    - name: Push dependencies
      run: |
        eval $(minikube docker-env)
        docker build -t ghcr.io/${{ github.repository }}/generic-test-app:main resources/apps/generic-test-app

        # install the reference implementation
        kapp deploy -y -a cert-manager -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
        kapp deploy -y -a servicebinding-runtime -f https://github.com/servicebinding/runtime/releases/download/v0.1.1/servicebinding-runtime-v0.1.1.yaml
    - name: Conformance tests
      run: .github/resources/run_ci.sh
    - name: Collect diagnostics
      run: |
        set +o errexit
        set -o nounset
        set +o pipefail

        echo "##[group]kubectl get clusterworkloadresourcemappings.servicebinding.io"
          kubectl get clusterworkloadresourcemappings.servicebinding.io
        echo "##[endgroup]"
        echo "##[group]kubectl get servicebindings.servicebinding.io -A"
          kubectl get servicebindings.servicebinding.io -A
        echo "##[endgroup]"
        echo "##[group]kubectl describe servicebindings.servicebinding.io -A"
          kubectl describe servicebindings.servicebinding.io -A
        echo "##[endgroup]"
        echo "##[group]kapp list -A"
          ${KAPP} list -A
        echo "##[endgroup]"
        echo "##[group]kubectl get all -n servicebinding-system"
          kubectl get all -n servicebinding-system
        echo "##[endgroup]"
        echo "##[group]kubectl get all -n servicebinding-cts"
          kubectl get all -n servicebindings-cts
        echo "##[endgroup]"
        echo "##[group]kubectl describe deployments.apps -n servicebinding-system"
          kubectl describe deployments.apps -n servicebinding-system
        echo "##[endgroup]"
        echo "##[group]kubectl describe deployments.apps -n servicebinding-cts"
          kubectl describe deployments.apps -n servicebindings-cts
        echo "##[endgroup]"
        echo "##[group]kubectl describe mutatingwebhookconfigurations.admissionregistration.k8s.io servicebinding-admission-projector"
          kubectl describe mutatingwebhookconfigurations.admissionregistration.k8s.io servicebinding-admission-projector
        echo "##[endgroup]"
        echo "##[group]kubectl describe validatingwebhookconfigurations.admissionregistration.k8s.io servicebinding-trigger"
          kubectl describe validatingwebhookconfigurations.admissionregistration.k8s.io servicebinding-trigger
        echo "##[endgroup]"
        echo "##[group]kubectl logs -n servicebinding-system -l control-plane=controller-manager --tail 10000"
          kubectl logs -n servicebinding-system -l control-plane=controller-manager --tail 10000
        echo "##[endgroup]"
      if: always()
      continue-on-error: true

