name: PR checks

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  it_runs:
    name: Run tests against reference implementation
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: "x64"
    - uses: vmware-tanzu/carvel-setup-action@v1
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up kubeconfig
      run: |
        KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
        echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
    - name: Set up minikube
      uses: medyagh/setup-minikube@latest
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
    - name: Push dependencies
      run: |
        eval $(minikube docker-env)
        docker build -t ghcr.io/${{ github.repository }}/generic-test-app:main resources/apps/generic-test-app

        # install the reference implementation
        kapp deploy -y -a cert-manager -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
        kapp deploy -y -a servicebinding-runtime -f https://github.com/servicebinding/runtime/releases/download/v0.2.0/servicebinding-runtime-v0.2.0.yaml
    - name: Conformance tests
      run: .github/resources/run_ci.sh
